/**
 * Regenerates the docs site's command reference, `docs-site/src/content/docs/reference/commands.md`,
 * from the desktop app's command catalog, so the published shortcuts can never drift from the app.
 *
 * `node scripts/docs-commands.ts` writes the page; `node scripts/docs-commands.ts --check` exits
 * non-zero when the committed page is out of date (this runs as part of `pnpm check`). Both source
 * modules are DOM-free and carry only type imports, so Node loads them straight from source.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { COMMAND_CATALOG, type CommandCatalogEntry } from '../apps/desktop/src/shared/command-catalog.ts';
import { formatKeybinding } from '../apps/desktop/src/shared/keybinding-format.ts';

const target = fileURLToPath(new URL('../docs-site/src/content/docs/reference/commands.md', import.meta.url));

/** Every binding that runs `entry`, its rebindable `shortcut` first, in one platform's spelling. */
function keysFor(entry: CommandCatalogEntry, platform: 'mac' | 'win'): string {
  const bindings = [entry.shortcut, ...(entry.extraShortcuts ?? [])].filter((b): b is string => b !== undefined);
  if (bindings.length === 0) {
    return '—';
  }
  return bindings.map((binding) => `<kbd>${formatKeybinding(binding, platform)}</kbd>`).join(' or ');
}

/** Escapes the characters that would break a Markdown table cell. */
function cell(text: string): string {
  return text.replaceAll('|', '\\|');
}

/**
 * The command reference page for `entries`, grouped by category in the order each category first
 * appears, commands in catalog order within a group.
 */
export function renderCommandReference(entries: readonly CommandCatalogEntry[]): string {
  const groups = new Map<string, CommandCatalogEntry[]>();
  for (const entry of entries) {
    const group = groups.get(entry.category) ?? [];
    group.push(entry);
    groups.set(entry.category, group);
  }

  const lines = [
    '---',
    'title: Commands and shortcuts',
    'description: Every command in the command palette and the keys that run it.',
    '---',
    '',
    "<!-- Generated by `pnpm docs:commands` from the app's command catalog. Do not edit by hand. -->",
    '',
    'Every command can be run from the command palette (<kbd>⌘K</kbd> on macOS, <kbd>Ctrl+K</kbd> on',
    'Windows and Linux). The first shortcut listed for a command can be changed in',
    '**Preferences → Shortcuts**; this page shows the defaults.',
  ];
  for (const [category, group] of groups) {
    lines.push('', `## ${category}`, '', '| Command | macOS | Windows and Linux |', '| --- | --- | --- |');
    for (const entry of group) {
      lines.push(`| ${cell(entry.label)} | ${keysFor(entry, 'mac')} | ${keysFor(entry, 'win')} |`);
    }
  }
  return `${lines.join('\n')}\n`;
}

async function main(): Promise<void> {
  const rendered = renderCommandReference(Object.values(COMMAND_CATALOG));
  const check = process.argv.includes('--check');
  const current = await readFile(target, 'utf-8').catch(() => undefined);

  if (current === rendered) {
    process.stdout.write('docs-site reference/commands.md is up to date\n');
    return;
  }
  if (check) {
    process.stderr.write('docs-site reference/commands.md is out of date; run `pnpm docs:commands`\n');
    process.exitCode = 1;
    return;
  }
  await writeFile(target, rendered, 'utf-8');
  process.stdout.write(`Wrote ${target}\n`);
}

if (process.argv[1] !== undefined && import.meta.url === new URL(process.argv[1], 'file:').href) {
  await main();
}
