/**
 * Renders the assertion catalogue as Markdown.
 *
 * `docs/ws-i-assertions.md` is generated from this by `scripts/wsi-docs.ts` (`pnpm wsi:docs`), and
 * `scripts/wsi-docs.test.ts` fails when the committed file drifts from the registry — the registry
 * stays the single source of truth.
 */

import type { WsiAssertion, WsiAssertionLevel } from './types.js';
import { WSI_WSDL_ASSERTIONS } from './assertions/index.js';

/** One assertion the catalogue names but does not implement yet. */
export interface PlannedAssertion {
  readonly id: string;
  readonly level: WsiAssertionLevel;
  readonly title: string;
  readonly notes: string;
}

/**
 * Assertions within the ranges the catalogue covers that are known to be missing, so the generated
 * document states the gap instead of implying the profile is fully covered.
 */
export const WSI_PLANNED_ASSERTIONS: readonly PlannedAssertion[] = Object.freeze([
  {
    id: 'R2004',
    level: 'REQUIRED',
    title: 'An xs:import must not name a document whose root element is not xs:schema',
    notes: 'Needs the resolver to keep documents it could not classify as a schema.',
  },
  {
    id: 'R2113',
    level: 'REQUIRED',
    title: 'An envelope must not carry soapenc:arrayType on an element in a message',
    notes:
      'Message-level, not description-level: moved out of the WSDL catalogue and into the message ' +
      'assertions (Task 44). The description-level array rules stay here as R2110/R2111.',
  },
  {
    id: 'R2114',
    level: 'REQUIRED',
    title: 'A description’s schema constructs stay within the profile’s XML Schema subset',
    notes: 'Id and requirement text not verified against the published profile.',
  },
  {
    id: 'R2202',
    level: 'RECOMMENDED',
    title: 'A description prefers the wrapped document-literal convention',
    notes: 'Planned.',
  },
  {
    id: 'R2207',
    level: 'REQUIRED',
    title: 'A wsdl:message part uses either the element or the type attribute, not both',
    notes: 'Id and requirement text not verified against the published profile.',
  },
  {
    id: 'R2208',
    level: 'REQUIRED',
    title: 'An rpc-literal operation’s parameterOrder names only parts of its messages',
    notes: 'Id and requirement text not verified against the published profile.',
  },
  {
    id: 'R2211',
    level: 'REQUIRED',
    title: 'An rpc-literal envelope must not carry xsi:nil on a part accessor',
    notes: 'Message-level; part of the message assertion catalogue.',
  },
  {
    id: 'R2301',
    level: 'REQUIRED',
    title: 'The order of body children matches the order of the wsdl:parts',
    notes: 'Message-level; part of the message assertion catalogue.',
  },
  {
    id: 'R2302',
    level: 'REQUIRED',
    title: 'An rpc-literal envelope names its part accessors after the wsdl:parts',
    notes: 'Message-level; part of the message assertion catalogue.',
  },
  {
    id: 'R2305',
    level: 'REQUIRED',
    title: 'A document-literal envelope carries the element declared by the bound part',
    notes: 'Message-level; part of the message assertion catalogue.',
  },
  {
    id: 'R2707',
    level: 'REQUIRED',
    title: 'Every soapbind element states the use attribute explicitly',
    notes: 'R2706 only checks the ones that state it; stating it is a separate requirement.',
  },
  {
    id: 'R2724',
    level: 'REQUIRED',
    title: 'An instance places the parts a soapbind:header names in the SOAP header',
    notes: 'Message-level; id and requirement text not verified against the published profile.',
  },
  {
    id: 'R2725',
    level: 'REQUIRED',
    title: 'An instance places the parts a soapbind:headerfault names in a header fault',
    notes: 'Message-level; id and requirement text not verified against the published profile.',
  },
  {
    id: 'R2726',
    level: 'REQUIRED',
    title: 'An instance must not carry a soapbind:header part the binding does not declare',
    notes: 'Message-level; id and requirement text not verified against the published profile.',
  },
  {
    id: 'R2802',
    level: 'REQUIRED',
    title: 'The description declares the WSDL 1.1 namespaces the profile mandates',
    notes: 'Planned.',
  },
]);

/** Escapes the pipe characters that would break a Markdown table cell. */
function cell(value: string): string {
  return value.replace(/\|/g, '\\|');
}

/**
 * Renders the catalogue: one table of implemented assertions and one of the known gaps.
 *
 * @param assertions the implemented catalogue (defaults to the registry)
 * @param planned the known gaps (defaults to {@link WSI_PLANNED_ASSERTIONS})
 */
export function renderWsiAssertionsMarkdown(
  assertions: readonly WsiAssertion[] = WSI_WSDL_ASSERTIONS,
  planned: readonly PlannedAssertion[] = WSI_PLANNED_ASSERTIONS,
): string {
  const lines: string[] = [
    '# WS-I Basic Profile 1.1 assertions',
    '',
    '<!--',
    '  Generated by `pnpm wsi:docs` from packages/engine/src/validate/wsi/assertions/index.ts.',
    '  Do not edit by hand: `pnpm wsi:docs --check` (and scripts/wsi-docs.test.ts) fail on drift.',
    '-->',
    '',
    `Wirebench implements ${assertions.length} WSDL-level assertions of the WS-I Basic Profile 1.1.`,
    'Each is evaluated against a description and reports `passed`, `failed` (a `REQUIRED`',
    'assertion), `warning` (a `RECOMMENDED` one) or `notApplicable` when the construct it examines',
    'does not occur. Profile requirement text is paraphrased; see the profile itself for the',
    'normative wording.',
    '',
    'A row marked *id unverified* implements a requirement Wirebench is confident about but whose',
    'requirement **number** could not be confirmed against the published profile; treat the id as',
    'provisional. The Planned table lists every id in the ranges this catalogue covers',
    '(`R2001`–`R2005`, `R2101`–`R2114`, `R2201`–`R2211`, `R2301`–`R2305`, `R2401`, `R2701`–`R2726`,',
    '`R2801`–`R2803`) that is known to be missing, so the coverage above is not overstated.',
    '',
    '## Implemented',
    '',
    '| Id | Level | Title | Status | Section |',
    '| --- | --- | --- | --- | --- |',
    ...assertions.map(
      (assertion) =>
        `| ${assertion.id} | ${assertion.level} | ${cell(assertion.title)} | ${
          assertion.unverifiedId === true ? 'Implemented (id unverified)' : 'Implemented'
        } | ${cell(assertion.section)} |`,
    ),
    '',
    '## Planned',
    '',
    '| Id | Level | Title | Status | Notes |',
    '| --- | --- | --- | --- | --- |',
    ...planned.map(
      (entry) => `| ${entry.id} | ${entry.level} | ${cell(entry.title)} | Planned | ${cell(entry.notes)} |`,
    ),
    '',
  ];
  return `${lines.join('\n')}`;
}
